#!/bin/sh

PATH_script_dir="`dirname $0`"

. "$PATH_script_dir/apk2gold.conf"

PATH_tools_dir="$PATH_script_dir/$TOOLS"

CMD_python2="python2"
CMD_java="java"
CMD_rreassoc="$CMD_python2 $PATH_script_dir/rreassoc.py"
CMD_dex2jar="$PATH_tools_dir/dex2jar-0.0.9.12/d2j-dex2jar.sh"
CMD_jd_cli="java -jar ${PATH_tools_dir}/jd-cli/jd-core-java-1.0.jar"
CMD_apktool="${PATH_tools_dir}/apktool/${HOST_OS}/apktool"

function die(){
    echo "$1"
    exit 1
}

if [ $# -lt 2 ]; then
    echo "usage:"
    echo "  $0 <output-dir> <apk-file> [another apk-file [...] ]"
    die
fi

PATH_out_dir="$1"
PATH_out_dir_tmp=$PATH_out_dir/.tmp

if ! [ -f "${PATH_script_dir}/${TAGS}/tag.${TAG}" ]; then
    echo "! It seems not to be prepared."
    echo "! Starting preparation script..."
    echo ""
    if ! "$PATH_script_dir/prepare.sh"
    then
	die "error: prepare.sh stopped by error."
    fi
    echo "Preparation successfully completed."
    echo ""
fi

shift

while [ $# -gt 0 ]; do
    if [ -d "$PATH_out_dir_tmp" ]; then
        echo "! temporary directory '$PATH_out_dir_tmp' already exists."
	echo "! removed."
        rm -r "$PATH_out_dir_tmp" 
        echo ""
    fi

    APK_filename="$1"
    APK_basename="`basename $APK_filename .apk`"
    APK_out_jar="$PATH_out_dir/${APK_basename}.d.jar"
    APK_src_dir="$PATH_out_dir_tmp/src"

    mkdir -p "$APK_src_dir"

    echo "### $APK_filename"
    echo "# .apk -> .smali, res"
    ( $CMD_apktool d -t "$TAG" -f "$APK_filename" "$PATH_out_dir_tmp" 2>&1 ) || die

    echo "# .apk -> .jar (.dex -> .class)"
    $CMD_dex2jar "$APK_filename" -o "$APK_out_jar" || die

    echo "# .class -> .java"
    $CMD_jd_cli "$APK_out_jar" "$APK_src_dir" || die

    echo "# reassosiate resources."
    $CMD_rreassoc "$PATH_out_dir_tmp" || die

    echo "# remove .jar"
    rm "$APK_out_jar"

    echo "# check move destination."
    if [ -d "$PATH_out_dir/$APK_basename" ]; then
	echo "'$PATH_out_dir/$APK_basename' already exists."
	echo "renamed."
	mv "$PATH_out_dir/$APK_basename" "$PATH_out_dir/${APK_basename}.moved.$(date +%s)"
    fi
    mv "$PATH_out_dir_tmp" "$PATH_out_dir/$APK_basename"

    echo "# done"
    echo ""

    shift
done

